import React, { Component } from 'react';
import PropTypes from 'prop-types';

import RealTable from 'dash-table/components/Table';

import 'dash-table/style/component.less';
import Logger from 'core/Logger';

export default class Table extends Component {
    render() {
        const {
            filtering,
            sorting,
            pagination_mode
        } = this.props;

        function isFrontEnd(value: any) {
            return ['fe', true, false].indexOf(value) !== -1;
        }

        function isBackEnd(value: any) {
            return ['be', false].indexOf(value) !== -1;
        }

        const isValid = isFrontEnd(pagination_mode) ||
            (isBackEnd(filtering) && isBackEnd(sorting));

        if (!isValid) {
            Logger.error(`Invalid combination of filtering / sorting / pagination`, filtering, sorting, pagination_mode);
            return (<div>Invalid props combination</div>);
        }

        return (<RealTable {...this.props} />);
    }
}

export const defaultProps = {
    pagination_mode: 'fe',
    pagination_settings: {
        displayed_pages: 1,
        current_page: 0,
        page_size: 250
    },
    navigation: 'page',

    content_style: 'fit',
    css: [],
    filtering: false,
    filtering_settings: '',
    filtering_type: 'basic',
    filtering_types: ['basic'],
    sorting: false,
    sorting_type: 'single',
    sorting_settings: [],

    derived_viewport_dataframe: [],
    derived_viewport_indices: [],
    derived_virtual_dataframe: [],
    derived_virtual_indices: [],

    column_conditional_dropdowns: [],
    column_static_dropdown: [],

    dataframe: [],
    columns: [],
    editable: false,
    active_cell: [],
    selected_cell: [[]],
    selected_rows: [],
    row_selectable: false,
    style: {}
};

export const propTypes = {
    active_cell: PropTypes.array,
    columns: PropTypes.arrayOf(PropTypes.object),
    content_style: PropTypes.oneOf(['fit', 'grow']),
    css: PropTypes.arrayOf(PropTypes.shape({
        selector: PropTypes.string,
        rule: PropTypes.string
    })),

    dataframe: PropTypes.arrayOf(PropTypes.object),
    dataframe_previous: PropTypes.arrayOf(PropTypes.object),
    dataframe_timestamp: PropTypes.any,

    editable: PropTypes.bool,
    end_cell: PropTypes.arrayOf(PropTypes.number),
    id: PropTypes.string.isRequired,
    is_focused: PropTypes.bool,
    merge_duplicate_headers: PropTypes.bool,
    n_fixed_columns: PropTypes.number,
    n_fixed_rows: PropTypes.number,
    row_deletable: PropTypes.bool,
    row_selectable: PropTypes.oneOf(['single', 'multi', false]),
    selected_cell: PropTypes.arrayOf(PropTypes.arrayOf(PropTypes.number)),
    selected_rows: PropTypes.arrayOf(PropTypes.number),
    setProps: PropTypes.any,
    start_cell: PropTypes.arrayOf(PropTypes.number),
    style_as_list_view: PropTypes.bool,

    pagination_mode: PropTypes.oneOf(['fe', 'be', true, false]),
    pagination_settings: PropTypes.shape({
        displayed_pages: PropTypes.number,
        current_page: PropTypes.number,
        page_size: PropTypes.number
    }),
    navigation: PropTypes.string,

    column_conditional_dropdowns: PropTypes.arrayOf(PropTypes.shape({
        id: PropTypes.string,
        dropdowns: PropTypes.arrayOf(PropTypes.shape({
            condition: PropTypes.string,
            dropdown: PropTypes.arrayOf(PropTypes.shape({
                label: PropTypes.string,
                value: PropTypes.any
            }))
        }))
    })),
    column_static_dropdown: PropTypes.arrayOf(PropTypes.shape({
        id: PropTypes.string,
        dropdown: PropTypes.arrayOf(PropTypes.shape({
            label: PropTypes.string,
            value: PropTypes.any
        }))
    })),

    filtering: PropTypes.oneOf(['fe', 'be', true, false]),
    filtering_settings: PropTypes.string,
    filtering_type: PropTypes.oneOf(['basic']),
    filtering_types: PropTypes.arrayOf(PropTypes.oneOf([
        'basic'
    ])),

    sorting: PropTypes.oneOf(['fe', 'be', true, false]),
    sorting_type: PropTypes.oneOf(['single', 'multi']),
    sorting_settings: PropTypes.arrayOf(
        PropTypes.shape({
            columnId: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            direction: PropTypes.oneOf(['asc', 'desc'])
        })),
    sorting_treat_empty_string_as_none: PropTypes.bool,
    style: PropTypes.shape({
        background: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
        background_attachment: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
        background_color: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
        background_image: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
        background_position: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
        background_repeat: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
        border: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
        border_bottom: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
        border_bottom_color: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
        border_bottom_style: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
        border_bottom_width: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
        border_color: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
        border_left: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
        border_left_color: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
        border_left_style: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
        border_left_width: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
        border_right: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
        border_right_color: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
        border_right_style: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
        border_right_width: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
        border_style: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
        border_top: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
        border_top_color: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
        border_top_style: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
        border_top_width: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
        border_width: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
        clear: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
        clip: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
        color: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
        cursor: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
        display: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
        filter: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
        float: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
        font: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
        font_family: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
        font_size: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
        font_variant: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
        font_weight: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
        height: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
        left: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
        letter_spacing: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
        line_height: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
        list_style: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
        list_style_image: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
        list_style_position: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
        list_style_type: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
        margin: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
        margin_bottom: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
        margin_left: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
        margin_right: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
        margin_top: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
        max_width: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
        min_width: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
        overflow: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
        padding: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
        padding_bottom: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
        padding_left: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
        padding_right: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
        padding_top: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
        page_break_after: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
        page_break_before: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
        position: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
        stroke_dasharray: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
        stroke_dashoffset: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
        stroke_width: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
        text_align: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
        text_decoration: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
        text_indent: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
        text_transform: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
        top: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
        vertical_align: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
        visibility: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
        width: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
        z_index: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),

        columns: PropTypes.arrayOf(PropTypes.shape({
            id: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            condition: PropTypes.string,
            background: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            background_attachment: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            background_color: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            background_image: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            background_position: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            background_repeat: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            border: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            border_bottom: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            border_bottom_color: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            border_bottom_style: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            border_bottom_width: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            border_color: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            border_left: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            border_left_color: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            border_left_style: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            border_left_width: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            border_right: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            border_right_color: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            border_right_style: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            border_right_width: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            border_style: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            border_top: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            border_top_color: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            border_top_style: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            border_top_width: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            border_width: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            clear: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            clip: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            color: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            cursor: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            display: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            filter: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            float: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            font: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            font_family: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            font_size: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            font_variant: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            font_weight: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            height: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            left: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            letter_spacing: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            line_height: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            list_style: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            list_style_image: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            list_style_position: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            list_style_type: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            margin: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            margin_bottom: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            margin_left: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            margin_right: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            margin_top: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            max_width: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            min_width: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            overflow: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            padding: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            padding_bottom: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            padding_left: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            padding_right: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            padding_top: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            page_break_after: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            page_break_before: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            position: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            stroke_dasharray: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            stroke_dashoffset: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            stroke_width: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            text_align: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            text_decoration: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            text_indent: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            text_transform: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            top: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            vertical_align: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            visibility: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            width: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            z_index: PropTypes.oneOfType([PropTypes.string, PropTypes.number])
        })),
        headers: PropTypes.arrayOf({
            id: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            condition: PropTypes.string,
            background: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            background_attachment: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            background_color: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            background_image: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            background_position: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            background_repeat: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            border: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            border_bottom: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            border_bottom_color: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            border_bottom_style: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            border_bottom_width: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            border_color: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            border_left: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            border_left_color: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            border_left_style: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            border_left_width: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            border_right: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            border_right_color: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            border_right_style: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            border_right_width: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            border_style: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            border_top: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            border_top_color: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            border_top_style: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            border_top_width: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            border_width: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            clear: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            clip: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            color: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            cursor: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            display: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            filter: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            float: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            font: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            font_family: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            font_size: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            font_variant: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            font_weight: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            height: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            left: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            letter_spacing: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            line_height: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            list_style: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            list_style_image: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            list_style_position: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            list_style_type: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            margin: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            margin_bottom: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            margin_left: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            margin_right: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            margin_top: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            max_width: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            min_width: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            overflow: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            padding: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            padding_bottom: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            padding_left: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            padding_right: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            padding_top: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            page_break_after: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            page_break_before: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            position: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            stroke_dasharray: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            stroke_dashoffset: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            stroke_width: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            text_align: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            text_decoration: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            text_indent: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            text_transform: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            top: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            vertical_align: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            visibility: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            width: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            z_index: PropTypes.oneOfType([PropTypes.string, PropTypes.number])
        }),
        rows: PropTypes.arrayOf({
            id: PropTypes.number,
            condition: PropTypes.string,
            background: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            background_attachment: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            background_color: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            background_image: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            background_position: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            background_repeat: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            border: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            border_bottom: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            border_bottom_color: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            border_bottom_style: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            border_bottom_width: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            border_color: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            border_left: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            border_left_color: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            border_left_style: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            border_left_width: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            border_right: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            border_right_color: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            border_right_style: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            border_right_width: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            border_style: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            border_top: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            border_top_color: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            border_top_style: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            border_top_width: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            border_width: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            clear: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            clip: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            color: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            cursor: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            display: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            filter: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            float: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            font: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            font_family: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            font_size: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            font_variant: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            font_weight: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            height: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            left: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            letter_spacing: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            line_height: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            list_style: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            list_style_image: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            list_style_position: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            list_style_type: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            margin: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            margin_bottom: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            margin_left: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            margin_right: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            margin_top: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            max_width: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            min_width: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            overflow: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            padding: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            padding_bottom: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            padding_left: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            padding_right: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            padding_top: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            page_break_after: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            page_break_before: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            position: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            stroke_dasharray: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            stroke_dashoffset: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            stroke_width: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            text_align: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            text_decoration: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            text_indent: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            text_transform: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            top: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            vertical_align: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            visibility: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            width: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
            z_index: PropTypes.oneOfType([PropTypes.string, PropTypes.number])
        })
    }),

    derived_viewport_dataframe: PropTypes.arrayOf(PropTypes.object),
    derived_viewport_indices: PropTypes.arrayOf(PropTypes.number),
    derived_virtual_dataframe: PropTypes.arrayOf(PropTypes.object),
    derived_virtual_indices: PropTypes.arrayOf(PropTypes.number),

    dropdown_properties: PropTypes.any,
};

Table.defaultProps = defaultProps;
Table.propTypes = propTypes;