componentPaths:
  - src/dash-table/dash/DataTable.js

recipes:
  - py
  - R

dist:
  - source: dash_table/bundle.js
    target: bundle.js
    external: true
  - source: dash_table/bundle.js.map
    target: bundle.js.map
    dynamic: true
    external: true
  - source: dash_table/async-export.js
    target: async-export.js
    async: true
    external: true
  - source: dash_table/async-export.js.map
    target: async-export.js.map
    dynamic: true
    external: true
  - source: dash_table/async-highlight.js
    target: async-highlight.js
    async: true
    external: true
  - source: dash_table/async-highlight.js.map
    target: async-highlight.js.map
    dynamic: true
    external: true
  - source: dash_table/async-table.js
    target: async-table.js
    async: true
    external: true
  - source: dash_table/async-table.js.map
    target: async-table.js.map
    dynamic: true
    external: true

vars:
  py:
    dist:
      - source: Format.py
        target: Format.py
      - source: FormatTemplate.py
        target: FormatTemplate.py

  R:
    prefix: dash
    depends:
    imports:
    suggests:
      - dash

    pkg_authors: c(person("Chris", "Parmer", email = "chris@plotly.com", role = c("aut")), person("Ryan Patrick", "Kyle", email = "ryan@plotly.com", role = c("cre"), comment = c(ORCID = "0000-0002-4958-2844")), person(family = "Plotly Technologies, Inc.", role = "cph"))
    pkg_help_description: ${js.core.readConfigFile('pkg_help_description.txt')}
    pkg_help_title: Core Interactive Table Component for 'Dash'
    pkg_copyright: Plotly Technologies, Inc.
    examples:
      DataTable:
        dontrun: false
        code: ${js.core.readConfigFile('dashDataTable.R')}
    dist:
      - source: df_to_list.Rd
        target: man/df_to_list.Rd
      - source: df_to_list.R
        target: R/df_to_list.R