# AUTO GENERATED FILE - DO NOT EDIT

dashDataTable <- function(id=NULL, active_cell=NULL, cell_selectable=NULL, column_selectable=NULL, columns=NULL, css=NULL, data=NULL, data_previous=NULL, data_timestamp=NULL, derived_filter_query_structure=NULL, derived_viewport_data=NULL, derived_viewport_indices=NULL, derived_viewport_row_ids=NULL, derived_viewport_selected_columns=NULL, derived_viewport_selected_row_ids=NULL, derived_viewport_selected_rows=NULL, derived_virtual_data=NULL, derived_virtual_indices=NULL, derived_virtual_row_ids=NULL, derived_virtual_selected_row_ids=NULL, derived_virtual_selected_rows=NULL, dropdown=NULL, dropdown_conditional=NULL, dropdown_data=NULL, editable=NULL, end_cell=NULL, export_columns=NULL, export_format=NULL, export_headers=NULL, fill_width=NULL, filter_action=NULL, filter_options=NULL, filter_query=NULL, fixed_columns=NULL, fixed_rows=NULL, hidden_columns=NULL, include_headers_on_copy_paste=NULL, is_focused=NULL, loading_state=NULL, locale_format=NULL, markdown_options=NULL, merge_duplicate_headers=NULL, page_action=NULL, page_count=NULL, page_current=NULL, page_size=NULL, persisted_props=NULL, persistence=NULL, persistence_type=NULL, row_deletable=NULL, row_selectable=NULL, selected_cells=NULL, selected_columns=NULL, selected_row_ids=NULL, selected_rows=NULL, sort_action=NULL, sort_as_null=NULL, sort_by=NULL, sort_mode=NULL, start_cell=NULL, style_as_list_view=NULL, style_cell=NULL, style_cell_conditional=NULL, style_data=NULL, style_data_conditional=NULL, style_filter=NULL, style_filter_conditional=NULL, style_header=NULL, style_header_conditional=NULL, style_table=NULL, tooltip=NULL, tooltip_conditional=NULL, tooltip_data=NULL, tooltip_delay=NULL, tooltip_duration=NULL, tooltip_header=NULL, virtualization=NULL) {
    
    props <- list(id=id, active_cell=active_cell, cell_selectable=cell_selectable, column_selectable=column_selectable, columns=columns, css=css, data=data, data_previous=data_previous, data_timestamp=data_timestamp, derived_filter_query_structure=derived_filter_query_structure, derived_viewport_data=derived_viewport_data, derived_viewport_indices=derived_viewport_indices, derived_viewport_row_ids=derived_viewport_row_ids, derived_viewport_selected_columns=derived_viewport_selected_columns, derived_viewport_selected_row_ids=derived_viewport_selected_row_ids, derived_viewport_selected_rows=derived_viewport_selected_rows, derived_virtual_data=derived_virtual_data, derived_virtual_indices=derived_virtual_indices, derived_virtual_row_ids=derived_virtual_row_ids, derived_virtual_selected_row_ids=derived_virtual_selected_row_ids, derived_virtual_selected_rows=derived_virtual_selected_rows, dropdown=dropdown, dropdown_conditional=dropdown_conditional, dropdown_data=dropdown_data, editable=editable, end_cell=end_cell, export_columns=export_columns, export_format=export_format, export_headers=export_headers, fill_width=fill_width, filter_action=filter_action, filter_options=filter_options, filter_query=filter_query, fixed_columns=fixed_columns, fixed_rows=fixed_rows, hidden_columns=hidden_columns, include_headers_on_copy_paste=include_headers_on_copy_paste, is_focused=is_focused, loading_state=loading_state, locale_format=locale_format, markdown_options=markdown_options, merge_duplicate_headers=merge_duplicate_headers, page_action=page_action, page_count=page_count, page_current=page_current, page_size=page_size, persisted_props=persisted_props, persistence=persistence, persistence_type=persistence_type, row_deletable=row_deletable, row_selectable=row_selectable, selected_cells=selected_cells, selected_columns=selected_columns, selected_row_ids=selected_row_ids, selected_rows=selected_rows, sort_action=sort_action, sort_as_null=sort_as_null, sort_by=sort_by, sort_mode=sort_mode, start_cell=start_cell, style_as_list_view=style_as_list_view, style_cell=style_cell, style_cell_conditional=style_cell_conditional, style_data=style_data, style_data_conditional=style_data_conditional, style_filter=style_filter, style_filter_conditional=style_filter_conditional, style_header=style_header, style_header_conditional=style_header_conditional, style_table=style_table, tooltip=tooltip, tooltip_conditional=tooltip_conditional, tooltip_data=tooltip_data, tooltip_delay=tooltip_delay, tooltip_duration=tooltip_duration, tooltip_header=tooltip_header, virtualization=virtualization)
    if (length(props) > 0) {
        props <- props[!vapply(props, is.null, logical(1))]
    }
    component <- list(
        props = props,
        type = 'DataTable',
        namespace = 'dash_table',
        propNames = c('id', 'active_cell', 'cell_selectable', 'column_selectable', 'columns', 'css', 'data', 'data_previous', 'data_timestamp', 'derived_filter_query_structure', 'derived_viewport_data', 'derived_viewport_indices', 'derived_viewport_row_ids', 'derived_viewport_selected_columns', 'derived_viewport_selected_row_ids', 'derived_viewport_selected_rows', 'derived_virtual_data', 'derived_virtual_indices', 'derived_virtual_row_ids', 'derived_virtual_selected_row_ids', 'derived_virtual_selected_rows', 'dropdown', 'dropdown_conditional', 'dropdown_data', 'editable', 'end_cell', 'export_columns', 'export_format', 'export_headers', 'fill_width', 'filter_action', 'filter_options', 'filter_query', 'fixed_columns', 'fixed_rows', 'hidden_columns', 'include_headers_on_copy_paste', 'is_focused', 'loading_state', 'locale_format', 'markdown_options', 'merge_duplicate_headers', 'page_action', 'page_count', 'page_current', 'page_size', 'persisted_props', 'persistence', 'persistence_type', 'row_deletable', 'row_selectable', 'selected_cells', 'selected_columns', 'selected_row_ids', 'selected_rows', 'sort_action', 'sort_as_null', 'sort_by', 'sort_mode', 'start_cell', 'style_as_list_view', 'style_cell', 'style_cell_conditional', 'style_data', 'style_data_conditional', 'style_filter', 'style_filter_conditional', 'style_header', 'style_header_conditional', 'style_table', 'tooltip', 'tooltip_conditional', 'tooltip_data', 'tooltip_delay', 'tooltip_duration', 'tooltip_header', 'virtualization'),
        package = 'dashTable'
        )

    structure(component, class = c('dash_component', 'list'))
}
