.dashTable_js_metadata <- function() {
deps_metadata <- list(`dash_table` = structure(list(name = "dash_table",
version = "4.7.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async-export.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashTable",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dash_table` = structure(list(name = "dash_table",
version = "4.7.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async-table.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashTable",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dash_table` = structure(list(name = "dash_table",
version = "4.7.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async-highlight.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashTable",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dash_table` = structure(list(name = "dash_table",
version = "4.7.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async-export.js.map',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashTable",
all_files = FALSE, dynamic = TRUE), class = "html_dependency"),
`dash_table` = structure(list(name = "dash_table",
version = "4.7.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async-table.js.map',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashTable",
all_files = FALSE, dynamic = TRUE), class = "html_dependency"),
`dash_table` = structure(list(name = "dash_table",
version = "4.7.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async-highlight.js.map',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashTable",
all_files = FALSE, dynamic = TRUE), class = "html_dependency"),
`dash_table` = structure(list(name = "dash_table",
version = "4.7.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'bundle.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashTable",
all_files = FALSE), class = "html_dependency"),
`dash_table` = structure(list(name = "dash_table",
version = "4.7.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'bundle.js.map',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashTable",
all_files = FALSE, dynamic = TRUE), class = "html_dependency"))
return(deps_metadata)
}
